# Generated by Django 6.0.5 on 2026-05-13 21:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMuscular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ejercicios/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grupo_muscular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrenamientos.grupomuscular')),
            ],
            options={
                'ordering': ['grupo_muscular__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrenamientos.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='entrenamientos.rutina')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SerieRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('calentamiento', 'Calentamiento'), ('fallo', 'Al fallo')], default='normal', max_length=15)),
                ('repeticiones', models.PositiveIntegerField(default=10)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('rutina_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='entrenamientos.rutinaejercicio')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('duracion_min', models.PositiveIntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('rutina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='entrenamientos.rutina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrenamientos.ejercicio')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='entrenamientos.workout')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('calentamiento', 'Calentamiento'), ('fallo', 'Al fallo')], default='normal', max_length=15)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('repeticiones', models.PositiveIntegerField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('workout_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='entrenamientos.workoutejercicio')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
