# Generated by Django 6.0.5 on 2026-05-13 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMuscular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='nombre del grupo muscular')),
            ],
            options={
                'verbose_name': 'Grupo muscular',
                'verbose_name_plural': 'Grupos musculares',
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre de la rutina')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción de la rutina')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
            },
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('peso', models.PositiveIntegerField(blank=True, null=True, verbose_name='peso')),
                ('series', models.PositiveIntegerField(verbose_name='series')),
                ('repeticiones', models.PositiveIntegerField(verbose_name='repeticiones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_entrenamientos/', verbose_name='imagen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenamientos', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('grupo_muscular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrenamientos', to='entrenamientos.grupomuscular', verbose_name='grupo muscular')),
                ('rutina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrenamientos', to='entrenamientos.rutina', verbose_name='rutina')),
            ],
            options={
                'verbose_name': 'Entrenamiento',
                'verbose_name_plural': 'Entrenamientos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
