# Generated by Django 6.0.5 on 2026-05-14 15:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-hora_inicio']},
        ),
        migrations.RenameField(
            model_name='rutina',
            old_name='descripcion',
            new_name='notas',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='duracion_min',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='rutina',
        ),
        migrations.AddField(
            model_name='rutinaejercicio',
            name='superset_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rutinaejercicio',
            name='tiempo_descanso_seg',
            field=models.PositiveIntegerField(default=90, help_text='Descanso tras la serie'),
        ),
        migrations.AddField(
            model_name='serie',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serie',
            name='rm_estimado',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='hora_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='hora_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workout',
            name='rutina_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts_derivados', to='entrenamientos.rutina'),
        ),
        migrations.AddField(
            model_name='workout',
            name='volumen_total_kg',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workoutejercicio',
            name='superset_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serie',
            name='repeticiones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serie',
            name='tipo',
            field=models.CharField(choices=[('N', 'Normal'), ('W', 'Calentamiento'), ('F', 'Al fallo'), ('D', 'Drop Set')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='serierutina',
            name='tipo',
            field=models.CharField(choices=[('N', 'Normal'), ('W', 'Calentamiento'), ('F', 'Al fallo'), ('D', 'Drop Set')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='workout',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CarpetaRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='rutina',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas', to='entrenamientos.carpetarutina'),
        ),
    ]
