# Generated by Django 6.0.5 on 2026-05-15 14:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0002_alter_workout_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='carpeta',
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-fecha']},
        ),
        migrations.RenameField(
            model_name='rutina',
            old_name='notas',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='rutinaejercicio',
            name='superset_id',
        ),
        migrations.RemoveField(
            model_name='rutinaejercicio',
            name='tiempo_descanso_seg',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='completada',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='rm_estimado',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='rutina_base',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='volumen_total_kg',
        ),
        migrations.RemoveField(
            model_name='workoutejercicio',
            name='superset_id',
        ),
        migrations.AddField(
            model_name='workout',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workout',
            name='rutina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='entrenamientos.rutina'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='repeticiones',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='serie',
            name='tipo',
            field=models.CharField(choices=[('N', 'Normal'), ('W', 'Calentamiento'), ('F', 'Al fallo')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='serierutina',
            name='tipo',
            field=models.CharField(choices=[('N', 'Normal'), ('W', 'Calentamiento'), ('F', 'Al fallo')], default='N', max_length=1),
        ),
        migrations.DeleteModel(
            name='CarpetaRutina',
        ),
    ]
