# Generated by Django 6.0.5 on 2026-05-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0003_remove_rutina_carpeta_alter_workout_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serierutina',
            options={},
        ),
        migrations.RemoveField(
            model_name='serierutina',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='serierutina',
            name='peso_kg',
        ),
        migrations.RemoveField(
            model_name='serierutina',
            name='repeticiones',
        ),
        migrations.RemoveField(
            model_name='serierutina',
            name='tipo',
        ),
        migrations.AddField(
            model_name='serierutina',
            name='num_series',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='serie',
            name='repeticiones',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
